foreground              #e0e0e0
background              #d00b0710
selection_foreground    #d00b0710
selection_background    #a77ef5
cursor                  #e0e0e0
cursor_text_color       #d00b0710
url_color               #4e7aff
active_border_color     #a77ef5
inactive_border_color   #484d69
bell_border_color       #f0a32f
active_tab_foreground   #d00b0710
active_tab_background   #a77ef5
inactive_tab_foreground #e0e0e0
inactive_tab_background #d00b0710
tab_bar_background      #d00b0710
color0  #484d69
color8  #484d69
color1  #e52e4f
color9  #e52e4f
color2  #86c93f
color10 #86c93f
color3  #f0a32f
color11 #f0a32f
color4  #4e7aff
color12 #4e7aff
color5  #a77ef5
color13 #a77ef5
color6  #72cbff
color14 #72cbff
color7  #e0e0e0
color15 #e0e0e0
color16 #e01b1b24

