# トリガーキー
TriggerKey=
# プライマリの貼り付け
# PastePrimaryKey=
# エントリー数
# Number of entries=5
# パスワードマネージャーからのパスワードを表示しない
# IgnorePasswordFromPasswordManager=False
# パスワードをプレーンテキストとして表示する
# ShowPassword=False
# パスワードをクリアするまでの秒数
# ClearPasswordAfter=30

