# ~/.config/hypr/hyprlock.conf

# 背景画像
background {
    path = .config/hypr/img/simple.png
}

# 時計
clock {
    enabled = true
    position = 0.5, 0.4
    format = %H:%M
    font = JetBrainsMono Nerd Font
    color = rgba(255, 255, 255, 0.9)
}

# パスワード入力
input-field {
    position = 0.5, 0.55
    font = JetBrainsMono Nerd Font
    inner_color = rgba(255, 255, 255, 0.3)
    outer_color = rgba(255, 255, 255, 1)
    outline_thickness = 3
}
