# AGS_HYPR_CONFIG_DIR is set by hypr/ags.lua and ags/scripts/launch.sh.
source = $AGS_HYPR_CONFIG_DIR/colors/colors.conf
$font = JetBrainsMono Nerd Font

general {
    hide_cursor = true
}

background {
    monitor =
    path = $AGS_HYPR_CONFIG_DIR/img/simple.png
    blur_passes = 3
}

label {
    monitor =
    text = $TIME
    color = $primary
    font_size = 100
    font_family = $font
    position = 0, 150
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 3
    outer_color = $primary
    inner_color = $background
    font_color = $foreground
    check_color = $secondary
    fail_color = $error
    font_family = $font
    placeholder_text = Password
    position = 0, -50
    halign = center
    valign = center
}
