$background = rgb(121318)
$foreground = rgb(e3e1e9)
$primary = rgb(bac3ff)
$secondary = rgb(c3c5dd)
$tertiary = rgb(e5bad8)
$error = rgb(ffb4ab)

$active_border = rgb(bac3ff)
$inactive_border = rgb(39393f)