-- Generated by Matugen. Edit the template instead.
return {
    active_border = "rgb({{colors.primary.default.hex_stripped}})",
    inactive_border = "rgb({{colors.surface_bright.default.hex_stripped}})",
}
